#!/usr/bin/env perl

use strict;
use warnings;

$/ = '';
my $msg = <>;

# A ^_^ smiley denotes a <module> version release
$msg =~ /^[A-Z]{3}[A-Z_0-9]* +/ or $msg =~ /^\^_\^ .* +\d+\.\d+ +released/
	or die "Commit message must start with capital tag(API, DOC, TST ...)";
